version: '3'
services:
  arethusa:
    build:
      context: .
      dockerfile: Dockerfile-arethusa
    volumes:
      - ./arethusa/app:/arethusa/app
      - ./arethusa/dist:/arethusa/dist
      - ./arethusa/spec:/arethusa/spec
    ports:
      - 8081:8081
    environment:
      - PORT=8081
